[project]
name = "talk-37-marimo-notebooks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "folium>=0.19.4",
    "jupyter>=1.1.1",
    "marimo>=0.10.15",
    "modelskill>=1.1.0",
]
